version: '3.1'

services:
  subgraphs:
    build: ./src/subgraphs/weather
    container_name: weather_demo_subgraph
    env_file:
      - .env
    volumes:
      - ./src/subgraphs/weather:/app
    ports:
      - 4000:4000
 
volumes:
  pgdata: